# configuration for the github action : BetaHuhn/repo-file-sync-action
group:
  # prettier workflow
  - files:
      - source: code-analysis/.prettierrc
        dest: .prettierrc
      - source: code-analysis/.eslintrc
        dest: .eslintrc
    repos: |
      https://github.com/restqa/restqa@master
      https://github.com/restqa/restqapi@master
      https://github.com/restqa/faker-plugin@master
      https://github.com/restqa/cucumber-export@master
