# configuration for the github action : BetaHuhn/repo-file-sync-action
group:
  # prettier workflow
  - files:
      - source: code-analysis/.prettierrc
        dest: .prettierrc
    repos: |
      restqa/restqa@master
      restqa/restqapi@master
   # linter workflow
  - files:
      - source: code-analysis/.eslintrc
        dest: .eslintrc
    # TODO(tony-go): add other repositories
    repos: |
      restqa/restqa@master
      restqa/restqapi@master