name: Issue - Add Open Pair programming comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'pair with maintainer'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Download the template
        id: step_one
        run: |
             echo 'TEMPLATE<<EOF' >> $GITHUB_ENV
             curl https://raw.githubusercontent.com/restqa/.github/master/.github/issue-comments/open-pair-programming/olivierodo-template.md >> $GITHUB_ENV
             echo 'EOF' >> $GITHUB_ENV
      - name: Add comment on the issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ env.TEMPLATE }}
      - name: tweety
        uses: m1ner79/Github-Twittction@v1.0.1
        with:
            twitter_status: "Interesting by a new way of contributing to opensource? Pair with the maintainer on this issue. 🤩🦏  #pairprogramming #testautomation #apitesting #gherkin #softwaretesting ${{github.event.issue.html_url}}"
            twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }} 
            twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }} 
            twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }} 
            twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 
