name: Synchronize config file
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run Repo File Sync Action
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          CONFIG_PATH: .github/config/sync-config.yml
          BRANCH_PREFIX: restqa-sync
